language: python
python:
        - "3.3"
        - "3.4"
        - "3.5"

install: pip install -r requirements.txt
script:
- py.test ./Freelance/SU-MA-DO/test_unittest.py
- wget https://raw.githubusercontent.com/teracyhq/sphinx-deployment/develop/scripts/spxd.sh && chmod +x ./spxd.sh && ./spxd.sh -p ./docs
